apply plugin: 'com.android.library'
apply plugin: 'kotlin-parcelize'

group = 'expo.modules.modelcommonsnative'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()

def safeExtGet = { prop, fallback ->
  rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}

android {
  namespace 'expo.modules.modelcommonsnative'
  compileSdkVersion safeExtGet('compileSdkVersion', 36)

  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 24)
    targetSdkVersion safeExtGet('targetSdkVersion', 36)
    versionCode 1
    versionName '0.1.0'
    testInstrumentationRunner 'android.test.InstrumentationTestRunner'
  }

  buildFeatures {
    aidl true
  }
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
}
